# Generated by Django 3.2.12 on 2022-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0004_auto_20220320_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('rating', models.IntegerField(choices=[(0, '*'), (1, '**'), (2, '***'), (3, '****'), (4, '*****')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicianSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[(0, 'Internal medicine'), (1, 'Pediatrician'), (2, 'Family medicine'), (3, 'Dermatologist'), (4, 'Cardiologist'), (5, 'Endocrinologist'), (6, 'Gastroenterologist'), (7, 'Neurologist'), (8, 'Urologist')], max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
            ],
        ),
    ]
