# Generated by Django 3.2.12 on 2022-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0005_doctor_physicianspeciality_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianspeciality',
            name='speciality',
            field=models.IntegerField(choices=[(0, 'Internal medicine'), (1, 'Pediatrician'), (2, 'Family medicine'), (3, 'Dermatologist'), (4, 'Cardiologist'), (5, 'Endocrinologist'), (6, 'Gastroenterologist'), (7, 'Neurologist'), (8, 'Urologist')]),
        ),
    ]
