# Generated by Django 3.2.12 on 2022-03-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0006_alter_physicianspeciality_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment_app.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment_app.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='places',
            field=models.ManyToManyField(to='appointment_app.Place'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ManyToManyField(to='appointment_app.PhysicianSpeciality'),
        ),
    ]
