# Generated by Django 3.2.12 on 2022-04-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment_app', '0009_auto_20220328_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_2rotate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment_app.appointment')),
                ('user1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='appointment_app.patient')),
                ('user2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='appointment_app.patient')),
            ],
        ),
    ]
