# Generated by Django 3.2.12 on 2022-04-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0009_auto_20220328_2140'),
        ('rotation', '0002_rotation_user1_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='user2_appt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2_appt', to='appointment_app.appointment'),
        ),
    ]
